### ISSUE TITLE
Model Licensing

### ISSUE THREAD

**Issue by michalgrzyska** [FaceONNX/FaceONNX.Models#2]
I noticed that `FaceDetector.cs` is using YOLOv5s ONNX model. From what I see in [YOLOv5 license](https://github.com/ultralytics/yolov5/blob/master/LICENSE), this model is AGPL 3.0. Does it mean that FaceONNX project should be AGPL licensed rather than MIT?

**Comment by asiryan** [comment]
Hi there! I don't really know. I just license my source code, which was developed in C#. Truth be told I'm not worried about the model license, because I can change it out into something newer and smarter at any time regarding my research.

**Comment by michalgrzyska** [comment]
So basically, we have no idea whether FaceONNX can be used for commercial purpose?

**Comment by asiryan** [comment]
> So basically, we have no idea whether FaceONNX can be used for commercial purpose?

I do not prohibit its use for commercial purposes. Also, you can use older versions of FaceONNX which don't contain yolov5s face detector.
